create extension if not exists pgcrypto;

create table if not exists public.intent_runs (
  id uuid primary key,
  source_mode text not null,
  source_input text,
  taxonomy_version text not null,
  taxonomy_manifest jsonb not null default '{}'::jsonb,
  configuration jsonb not null default '{}'::jsonb,
  status text not null default 'completed' check (status in ('running', 'completed', 'failed')),
  prospect_count integer not null default 0,
  topic_row_count integer not null default 0,
  ledger_row_count integer not null default 0,
  summary jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.intent_prospects (
  id uuid primary key,
  run_id uuid not null references public.intent_runs(id) on delete cascade,
  linkedin_url text not null,
  public_identifier text,
  full_name text,
  headline text,
  current_company text,
  current_role_name text,
  employer_relation text,
  job_seeking_flag boolean not null default false,
  pic_routing_status text,
  pic_routing_reason text,
  data_completeness_score numeric(6,2),
  overall_signal_quality text,
  overall_signal_quality_score numeric(6,2),
  top_topics jsonb not null default '[]'::jsonb,
  summary jsonb not null default '{}'::jsonb,
  raw_profile jsonb,
  raw_file_name text,
  scrape_timestamp timestamptz,
  scored_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.intent_topic_scores (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.intent_runs(id) on delete cascade,
  prospect_id uuid not null references public.intent_prospects(id) on delete cascade,
  topic_id text not null,
  topic_name text not null,
  theme text,
  category text,
  topic_type text,
  affinity_score numeric(6,2),
  active_intent_score numeric(6,2),
  persistent_interest_score numeric(6,2),
  intent_score numeric(6,2),
  priority_score numeric(6,2),
  priority_tier text,
  cluster_coherence_score numeric(6,2),
  intent_level text,
  footprint_score numeric(6,2),
  footprint_label text,
  footprint_summary text,
  intent_date_range text,
  time_confidence text,
  taxonomy_version text,
  scrape_timestamp timestamptz,
  scored_at timestamptz not null default now(),
  last_signal_date timestamptz,
  dated_signal_count integer not null default 0,
  stale_dated_signal_count integer not null default 0,
  undated_signal_count integer not null default 0,
  most_recent_dated_signal_age_days integer,
  matched_sources jsonb not null default '[]'::jsonb,
  matched_evidence_snippets jsonb not null default '[]'::jsonb,
  source_families jsonb not null default '[]'::jsonb,
  validation_status text,
  change_vs_prior_run text,
  delta_intent_score numeric(6,2),
  previous_intent_date_range text
);

create table if not exists public.intent_signal_ledger (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.intent_runs(id) on delete cascade,
  prospect_id uuid not null references public.intent_prospects(id) on delete cascade,
  topic_id text not null,
  signal_id text not null,
  source_family text,
  source_type text,
  signal_text_snippet text,
  signal_date timestamptz,
  date_type text,
  signal_status text,
  signal_direction text,
  lexical_score numeric(8,4),
  semantic_score numeric(8,4),
  specificity_score numeric(8,4),
  match_score numeric(8,4),
  source_affinity_weight numeric(8,4),
  source_intent_weight numeric(8,4),
  source_quality_multiplier numeric(8,4),
  date_recency_weight numeric(8,4),
  role_longevity_multiplier numeric(8,4),
  transition_event_weight numeric(8,4),
  affinity_contribution numeric(12,6),
  active_intent_contribution numeric(12,6),
  persistent_interest_contribution numeric(12,6),
  penalty_name text,
  penalty_amount numeric(12,6) not null default 0,
  raw_net_signal_contribution numeric(12,6),
  guard_flags_triggered text,
  signal_explanation text,
  scored_at timestamptz not null default now()
);

create index if not exists intent_prospects_run_id_idx on public.intent_prospects(run_id);
create index if not exists intent_topic_scores_run_id_idx on public.intent_topic_scores(run_id);
create index if not exists intent_topic_scores_prospect_id_idx on public.intent_topic_scores(prospect_id);
create index if not exists intent_topic_scores_topic_id_idx on public.intent_topic_scores(topic_id);
create index if not exists intent_signal_ledger_run_id_idx on public.intent_signal_ledger(run_id);
create index if not exists intent_signal_ledger_prospect_id_idx on public.intent_signal_ledger(prospect_id);
create index if not exists intent_signal_ledger_topic_id_idx on public.intent_signal_ledger(topic_id);

alter table public.intent_runs enable row level security;
alter table public.intent_prospects enable row level security;
alter table public.intent_topic_scores enable row level security;
alter table public.intent_signal_ledger enable row level security;
