// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const RAW_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const USE_DEV_PROXY = import.meta.env.DEV && import.meta.env.VITE_SUPABASE_DEV_PROXY !== 'false';

const SUPABASE_URL = USE_DEV_PROXY
  ? import.meta.env.VITE_SUPABASE_DEV_PROXY_URL ||
    `${typeof window !== 'undefined' ? window.location.origin : 'http://localhost:8080'}/__supabase`
  : RAW_SUPABASE_URL;

if (!RAW_SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY in .env');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
